<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CekKendaraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'tanggal' => Carbon::now()->format('Y-m-d'),
                'waktu_masuk' => '08:00',
                'waktu_keluar' => '08:15',
                'nomor_polisi' => 'B 1234 ABC',
                'jenis_kendaraan' => 'Truk',
                'nama_driver' => 'Ahmad Suhendra',
                'perusahaan' => 'PT. Logistik Jaya',
                'tujuan' => 'Kirim Barang Material',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos',
                'catatan' => 'Kondisi kendaraan sangat baik',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal' => Carbon::now()->format('Y-m-d'),
                'waktu_masuk' => '08:30',
                'waktu_keluar' => '08:45',
                'nomor_polisi' => 'D 5678 XYZ',
                'jenis_kendaraan' => 'Pickup',
                'nama_driver' => 'Dedi Kurniawan',
                'perusahaan' => 'CV. Angkut Segera',
                'tujuan' => 'Ambil Barang Reject',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => false,
                'kondisi_ban' => 'Kurang Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos Bersyarat',
                'catatan' => 'Ban depan kiri agak tipis, harap segera diganti',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal' => Carbon::now()->format('Y-m-d'),
                'waktu_masuk' => '09:00',
                'waktu_keluar' => '09:10',
                'nomor_polisi' => 'F 9101 GH',
                'jenis_kendaraan' => 'Mobil Box',
                'nama_driver' => 'Edi Gunawan',
                'perusahaan' => 'PT. Express Delivery',
                'tujuan' => 'Kirim Paket',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => false,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos Bersyarat',
                'catatan' => 'Spion kiri pecah',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal' => Carbon::now()->format('Y-m-d'),
                'waktu_masuk' => '09:15',
                'waktu_keluar' => null,
                'nomor_polisi' => 'DK 2233 JK',
                'jenis_kendaraan' => 'Tangki',
                'nama_driver' => 'Wayan Sudarma',
                'perusahaan' => 'PT. Air Minum Segar',
                'tujuan' => 'Isi Ulang Air',
                'surat_jalan' => false,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => true,
                'hasil_pemeriksaan' => 'Tidak Lolos',
                'catatan' => 'Terdapat kebocoran pada tangki air dan surat jalan tidak ada',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'tanggal' => Carbon::now()->subDay()->format('Y-m-d'),
                'waktu_masuk' => '10:00',
                'waktu_keluar' => '10:20',
                'nomor_polisi' => 'AB 4545 CC',
                'jenis_kendaraan' => 'Motor',
                'nama_driver' => 'Joko Susilo',
                'perusahaan' => 'Personal',
                'tujuan' => 'Bertemu Manager Gudang',
                'surat_jalan' => false,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => false,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos',
                'catatan' => 'Tamu kunjungan',
                'nama_petugas' => 'Siti Aminah',
                'created_at' => Carbon::now()->subDay(),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'tanggal' => Carbon::now()->subDay()->format('Y-m-d'),
                'waktu_masuk' => '11:00',
                'waktu_keluar' => '11:30',
                'nomor_polisi' => 'N 7788 UA',
                'jenis_kendaraan' => 'Truk',
                'nama_driver' => 'Bambang Pamungkas',
                'perusahaan' => 'PT. Semen Beton',
                'tujuan' => 'Kirim Semen',
                'surat_jalan' => true,
                'stnk_valid' => false,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Tidak Lolos',
                'catatan' => 'STNK Mati / Pajak telat 2 tahun',
                'nama_petugas' => 'Siti Aminah',
                'created_at' => Carbon::now()->subDay(),
                'updated_at' => Carbon::now()->subDay(),
            ],
            [
                'tanggal' => Carbon::now()->subDays(2)->format('Y-m-d'),
                'waktu_masuk' => '13:00',
                'waktu_keluar' => '13:15',
                'nomor_polisi' => 'L 9900 PP',
                'jenis_kendaraan' => 'Pickup',
                'nama_driver' => 'Kevin Sanjaya',
                'perusahaan' => 'CV. Teknik Maju',
                'tujuan' => 'Service AC Gudang',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Tidak Layak',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos Bersyarat',
                'catatan' => 'Lampu rem belakang mati sebelah kanan',
                'nama_petugas' => 'Rudi Hartono',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'tanggal' => Carbon::now()->subDays(2)->format('Y-m-d'),
                'waktu_masuk' => '14:30',
                'waktu_keluar' => '15:00',
                'nomor_polisi' => 'H 1212 XX',
                'jenis_kendaraan' => 'Mobil Box',
                'nama_driver' => 'Taufik Hidayat',
                'perusahaan' => 'PT. Buah Segar',
                'tujuan' => 'Kirim Buah',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => false,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Tidak Lolos',
                'catatan' => 'SIM Driver Expired',
                'nama_petugas' => 'Rudi Hartono',
                'created_at' => Carbon::now()->subDays(2),
                'updated_at' => Carbon::now()->subDays(2),
            ],
            [
                'tanggal' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'waktu_masuk' => '16:00',
                'waktu_keluar' => '16:45',
                'nomor_polisi' => 'BM 3434 ZZ',
                'jenis_kendaraan' => 'Tangki',
                'nama_driver' => 'Susi Susanti',
                'perusahaan' => 'PT. Minyak Goreng',
                'tujuan' => 'Ambil Limbah Minyak',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos',
                'catatan' => 'OK',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'tanggal' => Carbon::now()->subDays(3)->format('Y-m-d'),
                'waktu_masuk' => '07:00',
                'waktu_keluar' => '07:30',
                'nomor_polisi' => 'BK 5656 AA',
                'jenis_kendaraan' => 'Lainnya',
                'nama_driver' => 'Alan Budikusuma',
                'perusahaan' => 'Vendor Kebersihan',
                'tujuan' => 'Angkut Sampah',
                'surat_jalan' => true,
                'stnk_valid' => true,
                'sim_valid' => true,
                'kir_valid' => true,
                'kondisi_ban' => 'Kurang Baik',
                'kondisi_lampu' => 'Baik',
                'kaca_spion_lengkap' => true,
                'ada_kebocoran' => false,
                'hasil_pemeriksaan' => 'Lolos',
                'catatan' => 'Ban belakang vulkanisir',
                'nama_petugas' => 'Budi Santosu',
                'created_at' => Carbon::now()->subDays(3),
                'updated_at' => Carbon::now()->subDays(3),
            ],
        ];

        DB::table('cek_kendaraan')->insert($data);
    }
}
